name: floop
description: Dynamic values and animation API for Flutter widgets. Widgets rebuild automatically on dynamic values changes. Animate by transitioning a value in one function call.
version: 3.0.1
homepage: https://gitlab.com/ignacio_catalan/floop

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  mockito: ^4.1.0
  benchmark_harness:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
