name: floop_web
description: Dynamic values for Flutter Widgets. Web version of Floop.
version: 1.0.0
author: Ignacio Catalán <icata2016@gmail.com>
homepage: https://github.com/icatalud/floop

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter_web: ^1.0.0
    # git:
    #   url: https://github.com/flutter/flutter_web
    #   path: packages/flutter_web
  flutter_web_ui: ^1.0.0
    # git:
    #   url: https://github.com/flutter/flutter_web
    #   path: packages/flutter_web_ui

dev_dependencies:
  # flutter_web:
  #   git:
  #     url: https://github.com/flutter/flutter_web
  #     path: packages/flutter_web
  # flutter_web_ui:
  #   git:
  #     url: https://github.com/flutter/flutter_web
  #     path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  mockito:

dependency_overrides:
  # Should override flutter_web dependencies, but cannot publish to puv.dev
  # when overriding.

  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
