name: example

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  floop_web: ^1.0.0
    # path: ../floop_web
  flutter_web: ^1.0.0
    # git:
    #   url: https://github.com/flutter/flutter_web
    #   path: packages/flutter_web
  flutter_web_ui: ^1.0.0
    # git:
    #   url: https://github.com/flutter/flutter_web
    #   path: packages/flutter_web_ui

dependency_overrides:
  # Should override flutter_web dependencies, but cannot publish to puv.dev
  # when overriding.
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
