name: floop_benchmarks
description: Benchmarks for Floop
author: Ignacio Catalán <icata2016@gmail.com>
homepage: https://github.com/icatalud/floop

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  floop:
    # path: ../
    path: ../packages/floop

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  benchmark_harness: any

dependency_overrides:
  floop:
    # path: ../
    path: ../packages/floop
  
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
